[tests][objc] Make sure variables are declared with the right type. (#131)
Otherwise we might not be able to call methods, because clang will look for any matching selector in any type it knows about, which results compiler errors like:

```
In module 'XCTest' imported from /work/Embeddinator-4000/tests/objc-cli/libmanaged/Tests/Tests.m:1:
In module 'UIKit' imported from /Applications/Xcode83.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCUIElement.h:8:
/Applications/Xcode83.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAccelerometer.h:24:51: note: one possibility
@property(nonatomic,readonly) UIAccelerationValue x;
                                                  ^
In file included from /work/Embeddinator-4000/tests/objc-cli/libmanaged/Tests/Tests.m:3:
../build/test-framework-ios-temp-dir/iPhoneSimulator/managed.framework/Headers/managed.h:323:39: note: also found
@property (nonatomic, readonly) float x;
                                      ^
/work/Embeddinator-4000/tests/objc-cli/libmanaged/Tests/Tests.m:171:13: error: multiple methods named 'y' found with mismatched result, parameter type or attributes
        XCTAssert ([p2 y] == -2.0f, "y 2");
                   ^~~~~~
```

So by declaring the proper type for variables, clang doesn't have to guess.